name: WakaTime

options:
  bundleIdPrefix: macos-wakatime
  createIntermediateGroups: true

packages:
  Sparkle:
    url: https://github.com/sparkle-project/Sparkle
    from: 2.0.0
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk
    from: 10.0.0

targets:
  WakaTime:
    type: application
    platform: macOS
    deploymentTarget: 10.15
    sources: [WakaTime]
    settings:
      CURRENT_PROJECT_VERSION: local-build
      MARKETING_VERSION: local-build
      INFOPLIST_FILE: WakaTime/WakaTime-Info.plist
      GENERATE_INFOPLIST_FILE: YES
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: ${SV_DEVELOPMENT_TEAM}
      ENABLE_HARDENED_RUNTIME: YES
      DEAD_CODE_STRIPPING: YES
      SWIFT_OBJC_BRIDGING_HEADER: WakaTime/WakaTime-Bridging-Header.h
    postCompileScripts:
      - script: ./Scripts/Lint/swiftlint lint --quiet
        name: Swiftlint
    dependencies:
      - target: WakaTime Helper
      - package: Sparkle
      - package: Firebase
        product: FirebaseCrashlytics
    postBuildScripts:
      - script: |
          LOGIN_ITEMS_DIR="$BUILT_PRODUCTS_DIR/$PRODUCT_NAME.app/Contents/Library/LoginItems"
          rm -rf "$LOGIN_ITEMS_DIR"
          mkdir -p "$LOGIN_ITEMS_DIR"
          mv "$BUILT_PRODUCTS_DIR/$PRODUCT_NAME.app/Contents/Resources/WakaTime Helper.app" "$LOGIN_ITEMS_DIR/"
        name: Move "WakaTime Helper.app" to LoginItems
      - script: Scripts/Firebase/upload-dSYM.sh
        name: Firebase
        inputFiles:
          - ${DWARF_DSYM_FOLDER_PATH}/${DWARF_DSYM_FILE_NAME}/Contents/Resources/DWARF/${TARGET_NAME}
          - $(SRCROOT)/$(BUILT_PRODUCTS_DIR)/$(INFOPLIST_PATH)
  WakaTime Helper:
    type: application
    platform: macOS
    deploymentTarget: 10.15
    sources: [WakaTime Helper]
    settings:
      CURRENT_PROJECT_VERSION: local-build
      MARKETING_VERSION: local-build
      INFOPLIST_FILE: WakaTime Helper/WakaTime Helper-Info.plist
      GENERATE_INFOPLIST_FILE: YES
      CODE_SIGN_STYLE: Automatic
      DEVELOPMENT_TEAM: ${SV_DEVELOPMENT_TEAM}
      ENABLE_HARDENED_RUNTIME: YES
      DEAD_CODE_STRIPPING: YES
      SKIP_INSTALL: YES
    postCompileScripts:
      - script: ./Scripts/Lint/swiftlint lint --quiet
        name: Swiftlint
